services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redirector:
    build: .
    environment:
      - POSTGRESQL_URI=postgresql://root:rootpassword@postgres:5432/redirector
    ports:
      - "${PORT:-8080}:${PORT:-8080}"

volumes:
  postgres_data:
